{'author': 'Nedas Zilinskas',
 'category': 'Website',
 'currency': 'EUR',
 'data': ['security/res_groups.xml',
          'views/res_partner.xml',
          'views/res_partner_hcategory.xml',
          'views/forum_forum.xml'],
 'demo': [],
 'depends': ['website_forum', 'partner_category_hierarchy'],
 'external_dependencies': [],
 'images': ['static/description/main_screenshot.png'],
 'installable': True,
 'license': 'AGPL-3',
 'live_test_url': 'https://demo.minilini.com/page/start/website_forum_visibility/12.0',
 'name': 'Forum Visibility',
 'price': 20.0,
 'qweb': [],
 'summary': 'Forum Visibility by Partner Category',
 'support': 'nedas.zilinskas@gmail.com',
 'version': '12.0.1.0.0',
 'website': 'https://demo.minilini.com'}

